---
 
 - hosts: all
   become: true
   tasks:
 
   
 
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
 
 
 - hosts: web_servers
   become: true
   tasks:
 
   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   
 - hosts: db_servers
   become: true
   tasks: 
   - name: install mariadb server on Ubuntu
     tags: mariadb, ubuntu,db
     apt:
      name: mariadb-server
      state: latest
     when: ansible_distribution == "Ubuntu" 
